"""Browser regression check. Run a local server on 8765, then python tests/music-player.py.
Requires playwright and its Chromium browser (test dependencies only).
"""
from pathlib import Path
from playwright.sync_api import sync_playwright
import json

with sync_playwright() as p:
    browser = p.chromium.launch()
    context = browser.new_context(viewport={"width": 1440, "height": 1000})
    page = context.new_page()
    errors = []
    external_failures = []
    page.on('pageerror', lambda error: errors.append(str(error)))
    def record_console(msg):
        if msg.type != 'error': return
        url = msg.location.get('url', '')
        if url.startswith(('https://images.pexels.com/', 'https://videos.pexels.com/')):
            external_failures.append(url)  # Existing contact footage; unrelated to audio.
        else:
            errors.append(f'{msg.text} {msg.location}')
    page.on('console', record_console)
    page.goto('http://127.0.0.1:8765', wait_until='domcontentloaded')
    page.wait_for_function('typeof soundtrack !== "undefined" && soundtrack.readyState >= 1')
    page.wait_for_timeout(2200)
    assert page.evaluate('soundtrack.paused && playlist.length === 13')
    page.locator('.sound-toggle').click()
    page.wait_for_function('!soundtrack.paused && soundtrack.currentTime > 0.1')
    page.locator('.music-queue-toggle').click()
    # Every actual file must decode and play in the browser, including AAC-in-MP4.
    for i in range(13):
        page.locator('.music-queue button').nth(i).click()
        page.wait_for_function(f'trackIndex === {i} && !soundtrack.paused && soundtrack.currentTime > 0.05')
        assert page.evaluate('Number.isFinite(soundtrack.duration) && !soundtrack.error')
    print('PASS: all 13 tracks decode and play')
    page.locator('.sound-toggle').click()
    position = page.evaluate('soundtrack.currentTime')
    page.wait_for_timeout(200)
    assert page.evaluate('soundtrack.paused')
    assert abs(page.evaluate('soundtrack.currentTime') - position) < .05
    page.locator('.sound-toggle').click()
    page.wait_for_function('!soundtrack.paused')
    page.locator('.music-play').click()
    assert page.evaluate('soundtrack.paused')
    page.locator('.music-play').click()
    page.wait_for_function('!soundtrack.paused')
    page.locator('.music-seek').fill('500')
    page.wait_for_timeout(300)
    assert abs(page.evaluate('soundtrack.currentTime / soundtrack.duration') - .5) < .02
    page.locator('.music-previous').click()
    assert page.evaluate('trackIndex === 12 && soundtrack.currentTime < 2')
    page.locator('.music-previous').click()
    page.wait_for_function('trackIndex === 11 && !soundtrack.paused')
    page.locator('.music-next').click()
    page.wait_for_function('trackIndex === 12 && !soundtrack.paused')
    page.locator('.music-volume').fill('0.32')
    assert page.evaluate('soundtrack.volume === 0.32')
    page.locator('.music-mute').click()
    assert page.evaluate('soundtrack.muted')
    page.locator('.music-mute').click()
    assert not page.evaluate('soundtrack.muted')
    print('PASS: on/off, pause/resume, seek, previous restart/back, next, volume, mute')
    page.locator('.music-shuffle').click()
    sequence = [page.evaluate('trackIndex')]
    for _ in range(12):
        page.locator('.music-next').click()
        page.wait_for_function('!soundtrack.paused && soundtrack.readyState >= 2')
        sequence.append(page.evaluate('trackIndex'))
    assert len(set(sequence)) == 13, sequence
    page.evaluate('soundtrack.currentTime = 0')
    page.locator('.music-previous').click()
    assert page.evaluate('trackIndex') == sequence[-2]
    page.locator('.music-shuffle').click()
    prior = page.evaluate('trackIndex')
    page.locator('.music-next').click()
    assert page.evaluate('trackIndex') == (prior + 1) % 13
    print('PASS: shuffle visits every song once, history, normal order restored')
    page.locator('.music-queue button').nth(12).click()
    page.wait_for_function('soundtrack.readyState >= 2 && !soundtrack.paused')
    # Genuine end-of-media events exercise all repeat modes.
    page.locator('.music-repeat').click()
    assert page.evaluate('repeat === "song"')
    page.evaluate('soundtrack.currentTime = soundtrack.duration - 0.15')
    page.wait_for_function('trackIndex === 12 && soundtrack.currentTime < 2 && !soundtrack.paused')
    page.locator('.music-repeat').click()
    assert page.evaluate('repeat === "off"')
    page.evaluate('soundtrack.currentTime = soundtrack.duration - 0.15')
    page.wait_for_function('soundtrack.ended && soundtrack.paused')
    assert page.evaluate('trackIndex === 12')
    page.locator('.music-repeat').click()
    page.locator('.music-play').click()
    page.wait_for_function('!soundtrack.paused')
    page.evaluate('soundtrack.currentTime = soundtrack.duration - 0.15')
    page.wait_for_function('trackIndex === 0 && !soundtrack.paused')
    page.wait_for_function('soundtrack.readyState >= 2')
    page.evaluate('soundtrack.currentTime = soundtrack.duration - 0.15')
    page.wait_for_function('trackIndex === 1 && !soundtrack.paused')
    print('PASS: repeat song, repeat off at end, repeat playlist, auto advance')
    for theme in ('studio', 'night', 'day'):
        page.locator('.theme-toggle').click()
        page.locator(f'[data-theme-choice="{theme}"]').click()
        page.wait_for_function(f'document.documentElement.dataset.theme === "{theme}"')
        page.wait_for_function('!themeChanging')
        assert not page.evaluate('soundtrack.paused')
    page.mouse.wheel(0, 1800)
    page.wait_for_timeout(500)
    assert not page.evaluate('soundtrack.paused')
    page.locator('.archive-journey').evaluate('(el) => window.scrollTo(0, window.scrollY + el.getBoundingClientRect().top + 100)')
    page.wait_for_timeout(500)
    assert not page.evaluate('soundtrack.paused')
    car = page.locator('.road-car').bounding_box()
    page.mouse.move(car['x'] + car['width']/2, car['y'] + car['height']/2)
    page.mouse.down()
    page.mouse.move(car['x'] + car['width']/2, car['y'] + car['height']/2 + 80, steps=10)
    page.mouse.up()
    assert not page.evaluate('soundtrack.paused')
    core = page.locator('.contact-emblem')
    core.scroll_into_view_if_needed()
    core_box = core.bounding_box()
    page.mouse.move(core_box['x'] + core_box['width']/2, core_box['y'] + core_box['height']/2)
    page.mouse.down()
    page.mouse.move(core_box['x'] + core_box['width']/2 + 15, core_box['y'] + core_box['height']/2 + 15, steps=5)
    page.mouse.up()
    assert not page.evaluate('soundtrack.paused')
    page.locator('.to-top').evaluate('(el) => el.click()')
    assert not page.evaluate('soundtrack.paused')
    # Existing project view through its real UI handler, irrespective of scroll scene.
    project = page.locator('[data-project]').first
    if project.count():
        project.evaluate('(el) => el.click()')
        page.wait_for_timeout(400)
        assert not page.evaluate('soundtrack.paused')
        page.keyboard.press('Escape')
    print('PASS: themes, scrolling, Project Mode, car drag and footer retain playback')
    page.locator('.music-shuffle').click()
    page.locator('.music-repeat').click()
    page.evaluate('soundtrack.currentTime = 42; saveMusicState()')
    page.reload(wait_until='domcontentloaded')
    page.wait_for_function('typeof soundtrack !== "undefined" && soundtrack.readyState >= 1')
    assert page.evaluate('soundtrack.paused && trackIndex === 1 && Math.abs(soundtrack.currentTime - 42) < 1 && soundtrack.volume === .32 && shuffle && repeat === "song"')
    page.locator('.sound-toggle').click()
    page.wait_for_function('!soundtrack.paused && soundtrack.currentTime >= 42')
    page.locator('.music-queue-toggle').click()
    page.wait_for_timeout(350)
    Path('tests/artifacts').mkdir(exist_ok=True)
    page.locator('.music-player').screenshot(path='tests/artifacts/music-desktop.png')
    print('PASS: refresh restores track/time/volume without autoplay')
    mobile = browser.new_page(viewport={"width": 390, "height": 844})
    mobile.on('pageerror', lambda error: errors.append(str(error)))
    mobile.on('console', record_console)
    mobile.goto('http://127.0.0.1:8765', wait_until='domcontentloaded')
    mobile.wait_for_timeout(2200)
    mobile.locator('.sound-toggle').click()
    assert 'is-collapsed' in mobile.locator('.music-player').get_attribute('class')
    mobile.locator('.music-collapse').click()
    mobile.locator('.music-queue-toggle').click()
    mobile.wait_for_timeout(350)
    box = mobile.locator('.music-player').bounding_box()
    assert box['x'] >= 0 and box['x'] + box['width'] <= 390 and box['y'] >= 0 and box['y'] + box['height'] <= 844
    mobile.screenshot(path='tests/artifacts/music-mobile.png')
    mobile.locator('.music-queue button').nth(3).click()
    mobile.wait_for_function('trackIndex === 3 && !soundtrack.paused')
    mobile.locator('.music-collapse').click()
    assert mobile.locator('.music-details').evaluate('(el) => el.inert')
    print('PASS: mobile collapse, expand, queue selection, viewport bounds')
    # Simulate a decoder failure without deliberately creating a network console error.
    page.evaluate('soundtrack.dispatchEvent(new Event("error"))')
    page.wait_for_function('failedTracks.size === 1 && trackIndex === 2 && !soundtrack.paused')
    assert page.locator('.music-queue button').nth(1).is_disabled()
    assert page.locator('.music-library-count').inner_text() == '12 TRACKS'
    page.evaluate('for (let i=0; i<playlist.length; i++) failedTracks.add(i); skipFailedTrack()')
    assert page.evaluate('soundtrack.paused')
    print('PASS: failed-track skip and all-failed termination')
    assert not errors, json.dumps(errors, indent=2)
    print('PASS: no JavaScript errors or local resource errors')
    if external_failures:
        print('EXISTING EXTERNAL FAILURES:', json.dumps(sorted(set(external_failures))))
    browser.close()
